name: Deploy to Google Cloud Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ vars.CICD_GCP_PROJECTID }}

    - name: Authenticate with service account
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.CICD_GCP }}

    - name: Set Project ID
      run: gcloud config set project ${{ vars.CICD_GCP_PROJECTID }}

    - name: Deploy to Google Cloud Functions
      run: |
        gcloud functions deploy weather_collector  \
        --allow-unauthenticated \
        --gen2 \
        --runtime python311 \
        --trigger-http \
        --entry-point weather_collector \
        --region europe-central2 \
        --source . \
        --service-account=gcpfunctions-sa@${{ vars.CICD_GCP_PROJECTID }}.iam.gserviceaccount.com    
        --set-env-vars OPENWEATHER_API_KEY=${{ secrets.OPENWEATHER_API_KEY }}
  